### ISSUE TITLE
No notes on hypothesis testing with mixed models :( 

### ISSUE THREAD

**Issue by jrubinstein** [m-clark/mixed-models-with-R#15]
Your deck is truly an excellent introduction to mixed models. I wish it had existed 3 years ago! 
One thing I think is missing is a note on how to do hypothesis testing using LME. 
I ended up using something like this 
```model.null <-lmer(metric~(1|user_id)+(1|days_in),data= experiment_session_df,REML=F)
    #adding groups fixed effect
      model.test <-lmer(metric~experiment_treat+
                           (1|user_id)+(1|days_in),data=experiment_session_df,REML=F)
    # create a test
    anova(model.null,model.test) %>% 
      data.frame() %>%
      display(.)

    #display the model
    model.test %>%
      display(.) 
```

Where experiment_treat is the independent variable I really care about, but I want to extract the effect of user and time, while seeing the effect of time (days_in). 
It would be good to have something about doing these kinds of hypothesis tests in your guide. 
Cheers,
James

**Comment by m-clark** [comment]
Thanks for the comment and suggestion!  This might be something I could add, but the reason it's not in there is that I do model comparison with more prediction-oriented approaches if possible, and outlined my reasoning in the section on [model comparison](https://m-clark.github.io/mixed-models-with-R/issues.html#model-comparison).  Even so, I think you're right that it would probably be nice to have an explicit example rather than just describe the ratio test and AIC approaches.


Oh, and it did exist 3 years ago 😉, but it's much better now imho, so you probably didn't miss too much!

**Comment by m-clark** [comment]
I've added a small demo for the anova tables along with a tad more discussion.  Closing for now, but feel free to comment here for additional suggestions.
